@startuml

left to right direction
skinparam packageStyle rect
' skinparam linetype ortho

actor Guest

rectangle Sistem-Informasi-Indeks-Kepuasan-Masyarakat{
    Guest << Warga >>
    Guest -- (Melihat Daftar Kuesioner)
    (Melihat Daftar Kuesioner) <.. (Memilih Kuesioner): << extends >>
    Guest -- (Mengisi Kuesioner)
    (Memilih Kuesioner) -up- (Mengisi Kuesioner)
    (Mengisi Kuesioner) ..> (Mengisi Captcha): << include >>

}
@enduml
