@startuml Interaction Dashboard 2
autonumber
group Interaction Dashboard

    actor Admin 
    participant "<<boundary>>\nDashboard" as dashboard
    participant "<<control>>\nDashboardController" as dashboard_cont
    participant "<<entity>>\nrespondent" as respondent
    participant "<<entity>>\nquestionnaire" as questioner
    participant "<<entity>>\nuser" as admin
    participant "<<entity>>\nanswer" as answer

    Admin -> dashboard:Berhasil login
    activate dashboard
            dashboard -> dashboard_cont: Kirim perintah ambil data admin, \nquestionnaire, answer, respondent
        activate dashboard_cont
        dashboard_cont -> respondent:getRespondent()
        activate respondent
            dashboard_cont -> questioner:getQuestionnaire()
            activate questioner
                dashboard_cont -> admin:getAdmin()
                activate admin
                    dashboard_cont -> answer:getAnswer()
                    activate answer
                    respondent --> dashboard_cont:Terima data respondent
                    activate dashboard_cont
                        dashboard_cont->dashboard_cont:Hitung jumlah respondent
                    deactivate dashboard_cont
        deactivate respondent
                    questioner --> dashboard_cont:Terima data questionnaire
            deactivate questioner
                admin --> dashboard_cont:Terima data admin
                deactivate admin
                    answer --> dashboard_cont:Terima data answer
                    deactivate answer
                    activate dashboard_cont
                        dashboard_cont->dashboard_cont:Hitung jumlah answer
                    deactivate dashboard_cont
        dashboard_cont --> dashboard:Tampilkan Data
        deactivate dashboard_cont
    deactivate dashboard

end
@enduml