@startuml Interaction Dashboard
autonumber
group Interaction Dashboard

    actor Admin 
    participant "<<boundary>>\nDashboard" as dashboard
    participant "<<control>>\nDashboardController" as dashboard_cont
    participant "<<entity>>\nrespondent" as respondent
    participant "<<entity>>\nquestionnaire" as questioner
    participant "<<entity>>\nuser" as admin
    participant "<<entity>>\nanswer" as answer

    Admin -> dashboard:Berhasil login
    activate dashboard
            dashboard -> dashboard_cont:hitungDataResponden()
        activate dashboard_cont
            dashboard -> dashboard_cont:hitungDataQuestionnaire()
            dashboard -> dashboard_cont:tampilDataAdmin()
            dashboard -> dashboard_cont:hitungDataJawaban()
        dashboard_cont -> respondent:countRespondent()
        activate respondent
            dashboard_cont -> questioner:countQuestionnaire()
            activate questioner
                dashboard_cont -> admin:getAdmin()
                activate admin
                    dashboard_cont -> answer:countAnswer()
                    activate answer
                    respondent --> dashboard_cont:tampilHasilRespondent()
        deactivate respondent
                    questioner --> dashboard_cont:tampilHasilQuestionnaire()
            deactivate questioner
                admin --> dashboard_cont:tampilDataAdmin()
                deactivate admin
                    answer --> dashboard_cont:tampilHasilJawaban()
                    deactivate answer
        dashboard_cont --> dashboard:Tampilkan Data
        deactivate dashboard_cont
    deactivate dashboard

end
@enduml