@startuml Interaction Kelola Data
autonumber
' skinparam style strictuml
skinparam SequenceMessageAlignment center
group Interaction Kelola Kuesioner

    actor Admin 
    boundary "<<boundary>>\nList_Kuesioner" as list
    boundary "<<boundary>>\nDetail_List_Kuesioner" as dlist
    boundary "<<boundary>>\nCreate_questionnaire" as tquestionnaire
    boundary "<<boundary>>\nTambah_question" as tquestion
    boundary "<<boundary>>\nedit_questionnaire" as equestionnaire
    control "<<control>>\nDashboardQuiz\nController" as dqcontrol
    control "<<control>>\nController" as control
    entity "<<entity>>\nquestionnaire" as questioner
    entity "<<entity>>\nquestion" as question
    entity "<<entity>>\nrespondent" as respondent
    entity "<<entity>>\nuser" as admin
    entity "<<entity>>\nanswer" as answer



    group Seq Melihat Detail Kuesioner
        Admin-> dlist: Membuka halaman detail list kuesioner
        activate dlist
            dlist-> dqcontrol: tampilQuestionnaire()
                activate dqcontrol
                dlist-> dqcontrol: tampilQuestion()
                dlist-> dqcontrol: hitungRespondent()
                dlist-> dqcontrol: hitungAnswer()
                
                
                dqcontrol-> questioner: getQuestionnaire()
                activate questioner
                dqcontrol-> question: getQuestion()
                activate question
                dqcontrol-> respondent: countRespondent()
                activate respondent
                dqcontrol-> answer: getAnswer()
                activate answer

                questioner--> dqcontrol: tampilQuestionnaire()
                deactivate questioner
                question--> dqcontrol: tampilQuestion()
                deactivate question
                respondent--> dqcontrol: tampilHasilRespondent()
                deactivate respondent
                answer--> dqcontrol: tamnpilHasilAnswer()
                deactivate answer

                dqcontrol--> dlist: Tampilkan Detail Kuesioner
                deactivate dqcontrol
        deactivate dlist
        
    end

    group Seq Membuat Kuesioner
        Admin-> list: Membuka halaman list kuesioner
        activate list
            list-> tquestionnaire: Mengklik tombol Tambah Kuesioner
        deactivate list

        activate tquestionnaire
            tquestionnaire-> tquestion: Mengklik create post
        deactivate tquestionnaire

        activate tquestion
            tquestion-> control: tampilTambahQuestion()
            activate control
                control--> tquestion: Tampil form create question
            deactivate control
            tquestion-> dqcontrol: tambahQuestion()
            activate dqcontrol
            tquestion-> dqcontrol: tambahQuestionnaire()
        deactivate tquestion
        dqcontrol-> questioner: create()
        activate questioner
        dqcontrol-> question: input()
        activate question
        questioner--> dqcontrol: Berhasil ditambah
        deactivate questioner
        question--> dqcontrol: Berhasil ditambah
        deactivate question
        dqcontrol--> list: Notifikasi berhasil menambahkan
        activate list
        deactivate list
        deactivate dqcontrol
    end
    
    group Seq Mengedit Kuesioner
        Admin->dlist: Membuka halaman detail list kuesioner
        activate dlist
            dlist-> equestionnaire: Mengklik tombol Edit Kuesioner
        deactivate dlist
        activate equestionnaire
        equestionnaire-> dqcontrol: tampilEditQuestionnaire()
            activate dqcontrol
                dqcontrol--> equestionnaire: tampilFormEditQuestionnaire()
            deactivate dqcontrol
        equestionnaire-> dqcontrol: editQuestionnaire()
        activate dqcontrol
        equestionnaire-> dqcontrol: editQuestion()
        deactivate equestionnaire
        dqcontrol-> questioner: update()
        activate questioner
        dqcontrol-> question: update()
        activate question
        questioner--> dqcontrol: Berhasil diupdate
        deactivate questioner
        question--> dqcontrol: Berhasil diupdate
        deactivate question
        dqcontrol--> dlist: Notifikasi berhasil mengedit
        activate dlist
        deactivate dlist
        deactivate dqcontrol
    end

    group Seq Menghapus Kuesioner
        Admin-> dlist: Membuka halaman detail list kuesioner
        activate dlist
                dlist-> dlist: Mengklik tombol Hapus Kuesioner
            activate dlist
                dlist-> dqcontrol: hapusQuestionnaire()
            deactivate dlist
            
            activate dqcontrol
                dqcontrol-> questioner: delete()
            activate questioner
                dqcontrol-> question: delete()
            activate question
                questioner--> dqcontrol: Berhasil dihapus
            deactivate questioner
                question--> dqcontrol: Berhasil dihapus
            deactivate question
                dqcontrol--> dlist: Notifikasi berhasil menghapus
            deactivate dqcontrol
        deactivate dlist
    end
end
@enduml