@startuml Interaction Memilih Kuesioner
autonumber

actor "Guest" as A
boundary "Daftar_Kuesioner" as daftar
' boundary "Detail_Kuesioner" as detail    
control "PostController" as pcontrol
control "CaptchaController" as ccontrol
entity "Questionnaire" as q
' entity "Question" as qn

group Mengisi Kuesioner
    group Seq Melihat Daftar Kuesioner
        A -> daftar: Menekan tombol Pilih Kuesioner \npada landing page
        activate daftar
                daftar -> pcontrol: Tampil Data Kuesioner
                activate pcontrol
                pcontrol -> q: Get Data Kuesioner
                activate q
                q --> pcontrol: Tampil Data Kuesioner
                deactivate q
                pcontrol--> daftar: Tampil Daftar Kuesioner
            deactivate pcontrol
        deactivate daftar
    end
end
@enduml