@startuml Interaction Memilih Kuesioner
autonumber

actor "Guest" as A
participant "<<boundary>>\nDaftar_Kuesioner" as daftar
' participant "<<boundary>>\nDetail_Kuesioner" as detail    
participant "<<control>>\nPostController" as pcontrol
participant "<<control>>\nCaptchaController" as ccontrol
participant "<<entity>>\nQuestionnaire" as q
' participant "<<entity>>\nQuestion" as qn

group Mengisi Kuesioner
    group Seq Melihat Daftar Kuesioner
        A -> daftar: Menekan tombol Pilih Kuesioner \npada landing page
        activate daftar
                daftar -> pcontrol: Tampil Data Kuesioner
                activate pcontrol
                pcontrol -> q: Get Data Kuesioner
                activate q
                q --> pcontrol: Tampil Data Kuesioner
                deactivate q
                pcontrol--> daftar: Tampil Daftar Kuesioner
            deactivate pcontrol
        deactivate daftar
    end
end
@enduml