@startuml Interaction Dashboard
autonumber
group Interaction Melihat Daftar Kuesioner

    actor guest 
    participant "<<boundary>>\nHome" as home
    participant "<<boundary>>\nDaftar_Kuesioner" as daftar
    participant "<<control>>\nPostController" as pcontrol
    participant "<<entity>>\nquestionnaire" as questioner

    guest-> home: Berhasil Membuka Website
    activate home
        home-> daftar: Klik Pilih Kuesioner
    deactivate home
    
    activate daftar
        daftar-> pcontrol: tampilQuestionnaire()
            activate pcontrol
                pcontrol-> questioner: getQuestionnaire()
                activate questioner
                    questioner-> pcontrol: Data Questionnaire()
                deactivate questioner
                pcontrol-> daftar: tampilDaftarQuestionnaire()
            deactivate pcontrol
    deactivate daftar
end
@enduml