@startuml Interaction Mengisi Kuesioner
autonumber
skinparam SequenceMessageAlignment center

actor "Guest" as A
participant "Detail_Kuesioner" as detail
participant "Halaman_Kuesioner" as halaman    
participant "PostController" as pcontrol
participant "Questionnaire" as q
participant "Question" as qn      
        group Seq Melihat Detail Kuesioner
            A -> detail: Menekan tombol Pilih Kuesioner
            activate detail
                detail -> pcontrol: tampilQuestionnaire()
                activate pcontrol
                detail -> pcontrol: tampilQuestion()
                pcontrol -> q: getQuestionnaire()
                activate q
                pcontrol -> qn: getQuestion()
                activate qn
                q --> pcontrol: Tampil Data Kuesioner
                deactivate q
                qn --> pcontrol: Tampil Data Pertanyaan
                deactivate qn
                pcontrol--> detail: Tampil Detail Kuesioner
                deactivate pcontrol
                deactivate detail
        end
@enduml