@startuml Interaction Mengisi Kuesioner
autonumber
' skinparam SequenceMessageAlignment center

actor "Guest" as A
participant "<<boundary>>\nDetail_Kuesioner" as detail
participant "<<control>>\nPostController" as pcontrol
participant "<<entity>>\nQuestionnaire" as q
participant "<<entity>>\nQuestion" as qn      
        group Seq Melihat Detail Kuesioner Guest
            A -> detail: Menekan tombol Pilih Kuesioner
            activate detail
                detail -> pcontrol: tampilQuestionnaire()
                activate pcontrol
                detail -> pcontrol: tampilQuestion()
                pcontrol -> q: getQuestionnaire()
                activate q
                pcontrol -> qn: getQuestion()
                activate qn
                q --> pcontrol: tampilDataKuesioner()
                deactivate q
                qn --> pcontrol: tampilDataPertanyaan()
                deactivate qn
                pcontrol--> detail: Tampil Detail Kuesioner
                deactivate pcontrol
            deactivate detail
        end
@enduml