@startuml Interaction Dashboard
autonumber
group Interaction Dashboard

    actor Admin 
    participant "<<boundary>>\nDashboard" as dashboard
    participant "<<control>>\nDashboardController" as dashboard_cont
    participant "<<entity>>\nrespondent" as respondent
    participant "<<entity>>\nquestionnaire" as questioner
    participant "<<entity>>\nuser" as admin
    participant "<<entity>>\nanswer" as answer

    Admin -> dashboard:Berhasil login
    activate dashboard
            dashboard -> dashboard_cont:Hitung data responden
        activate dashboard_cont
            dashboard -> dashboard_cont:Hitung data kuesioner
            dashboard -> dashboard_cont:Tampil data admin
            dashboard -> dashboard_cont:Hitung data jawaban
        dashboard_cont -> respondent:Hitung data responden
        activate respondent
            dashboard_cont -> questioner:Hitung data kuesioner
            activate questioner
                dashboard_cont -> admin:getData()
                activate admin
                    dashboard_cont -> answer:Hitung data jawaban
                    activate answer
                    respondent --> dashboard_cont:Hasil responden
        deactivate respondent
                    questioner --> dashboard_cont:Hasil questioner
            deactivate questioner
                admin --> dashboard_cont:Tampil data admin
                deactivate admin
                    answer --> dashboard_cont:Hasil Jawaban
                    deactivate answer
        dashboard_cont --> dashboard:Tampilkan Data
        deactivate dashboard_cont
    deactivate dashboard

end
@enduml