@startuml tampilListKuesioner 2
autonumber
    actor Admin 
    participant "<<boundary>>\nList_Kuesioner" as list
    participant "<<control>>\nDashboardQuiz\nController" as dqcontrol
    participant "<<entity>>\nquestionnaire" as questioner
    participant "<<entity>>\nquestion" as question
    participant "<<entity>>\nrespondent" as respondent


    group Seq Menampilkan List Kuesioner
        Admin->list:Membuka halaman list kuesioner
        activate list
            list-> dqcontrol: Kirim perintah ambil data \nQuestionnaire, Question, Respondent
            activate dqcontrol
                dqcontrol-> questioner: getQuestionnaire()
                activate questioner
                    dqcontrol-> question:  getQuestion()
                activate question
                    dqcontrol-> respondent: getRespondent()
                activate respondent
                    questioner--> dqcontrol: Terima data Questionnaire
                deactivate questioner
                    question--> dqcontrol: Terima data Question
                deactivate question
                activate dqcontrol
                    dqcontrol ->dqcontrol: Hitung jumlah question
                deactivate dqcontrol
                    respondent--> dqcontrol: Terima data Respondent 
                deactivate respondent
                activate dqcontrol
                    dqcontrol ->dqcontrol: Hitung jumlah question
                deactivate dqcontrol
                dqcontrol--> list: Tampilkan List Kuesioner
            deactivate dqcontrol
        deactivate list
    end
@enduml
```